name: Docker Build And Push To GitHub Packages
on:
  push:
    tags:
      - v*

jobs:
  hub:
    name: Build and push hub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}-hub:${{ github.sha }}
          file: ./hub.Dockerfile

  peer:
    name: Build and push peer
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}-peer:${{ github.sha }}
          file: ./peer.Dockerfile

  watchtower:
    name: Trigger Watchtower CD
    needs: [hub, peer]
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Watchtower
        uses: wei/curl@master
        with:
          args: -H "Authorization: Bearer {{ secrets.WATCHTOWER_TOKEN }}" https://api.demedia.app/watchtower/v1/update
